/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.linkdroid;

public final class R {
    public static final class array {
        public static final int events_log_level_names=0x7f050002;
        public static final int events_log_level_values=0x7f050003;
        public static final int log_level_names=0x7f050000;
        public static final int log_level_values=0x7f050001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int intentfilter_edit_action_name=0x7f080000;
        public static final int intentfilter_edit_category_name=0x7f080001;
        public static final int intentfilter_edit_data_auth_host_name=0x7f080002;
        public static final int intentfilter_edit_data_auth_port_name=0x7f080003;
        public static final int intentfilter_edit_data_scheme_name=0x7f080004;
        public static final int intentfilter_edit_data_type_name=0x7f080005;
        public static final int intentfilter_edit_menu_cancel_item=0x7f08000c;
        public static final int intentfilter_edit_menu_save_item=0x7f08000b;
        public static final int intentfilters_list_context_menu_delete_item=0x7f08000e;
        public static final int intentfilters_list_context_menu_edit_item=0x7f08000d;
        public static final int intentfilters_list_menu_about_item=0x7f080011;
        public static final int intentfilters_list_menu_event_webhook_item=0x7f080010;
        public static final int intentfilters_list_menu_new_item=0x7f08000f;
        public static final int logs_list_menu_clear_item=0x7f080012;
        public static final int webhook_edit_menu_cancel_item=0x7f080014;
        public static final int webhook_edit_menu_save_item=0x7f080013;
        public static final int webhook_edit_name=0x7f080006;
        public static final int webhook_edit_nonce_random=0x7f080009;
        public static final int webhook_edit_nonce_timestamp=0x7f08000a;
        public static final int webhook_edit_secret=0x7f080008;
        public static final int webhook_edit_uri=0x7f080007;
        public static final int webhooks_list_context_menu_delete_item=0x7f080017;
        public static final int webhooks_list_context_menu_edit_item=0x7f080016;
        public static final int webhooks_list_context_menu_send=0x7f080018;
        public static final int webhooks_list_context_menu_send_extra=0x7f080019;
        public static final int webhooks_list_context_menu_set_events_webhook_item=0x7f080015;
        public static final int webhooks_list_menu_about_item=0x7f08001e;
        public static final int webhooks_list_menu_intentfilters_item=0x7f08001c;
        public static final int webhooks_list_menu_new_item=0x7f08001a;
        public static final int webhooks_list_menu_settings_item=0x7f08001d;
        public static final int webhooks_list_menu_view_log_item=0x7f08001b;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int about_intent_filters=0x7f030001;
        public static final int intentfilter_edit=0x7f030002;
        public static final int intentfilters_list=0x7f030003;
        public static final int logs_list=0x7f030004;
        public static final int webhook_edit=0x7f030005;
        public static final int webhooks_list=0x7f030006;
    }
    public static final class menu {
        public static final int intentfilter_edit_menu=0x7f070000;
        public static final int intentfilters_list_context_menu=0x7f070001;
        public static final int intentfilters_list_menu=0x7f070002;
        public static final int logs_list_menu=0x7f070003;
        public static final int webhook_edit_menu=0x7f070004;
        public static final int webhooks_list_context_menu=0x7f070005;
        public static final int webhooks_list_context_menu_send=0x7f070006;
        public static final int webhooks_list_menu=0x7f070007;
    }
    public static final class string {
        public static final int about_intent_filters_name=0x7f060003;
        public static final int about_intent_filters_text=0x7f060004;
        public static final int about_name=0x7f060001;
        public static final int about_text=0x7f060002;
        public static final int app_name=0x7f060000;
        public static final int broadcastreceiverservice_create=0x7f060006;
        public static final int broadcastreceiverservice_received_intent_prefix=0x7f060005;
        public static final int broadcastreceiverservice_start=0x7f060007;
        public static final int broadcastreceiverservice_stop=0x7f060008;
        public static final int intentfilter_edit_action_label=0x7f06000a;
        public static final int intentfilter_edit_category_label=0x7f06000b;
        public static final int intentfilter_edit_data_auth_host_label=0x7f06000c;
        public static final int intentfilter_edit_data_auth_port_label=0x7f06000d;
        public static final int intentfilter_edit_data_scheme_label=0x7f06000e;
        public static final int intentfilter_edit_data_type_label=0x7f06000f;
        public static final int intentfilter_edit_menu_cancel_label=0x7f060011;
        public static final int intentfilter_edit_menu_save_label=0x7f060010;
        public static final int intentfilter_edit_name=0x7f060009;
        public static final int intentfilter_import_cancelled=0x7f060012;
        public static final int intentfilter_import_io_error=0x7f060015;
        public static final int intentfilter_import_json_error=0x7f060014;
        public static final int intentfilter_import_saved=0x7f060013;
        public static final int intentfilters_list_context_menu_delete_label=0x7f06001c;
        public static final int intentfilters_list_context_menu_edit_label=0x7f06001b;
        public static final int intentfilters_list_dialog_delete_message=0x7f06001e;
        public static final int intentfilters_list_dialog_delete_title=0x7f06001d;
        public static final int intentfilters_list_empty_view=0x7f060017;
        public static final int intentfilters_list_menu_about_label=0x7f06001a;
        public static final int intentfilters_list_menu_event_webhook_label=0x7f060019;
        public static final int intentfilters_list_menu_new_label=0x7f060018;
        public static final int intentfilters_list_name=0x7f060016;
        public static final int logs_list_empty_view=0x7f060029;
        public static final int logs_list_menu_clear_label=0x7f06002a;
        public static final int logs_list_name=0x7f060028;
        public static final int misc_cancel_button=0x7f060023;
        public static final int misc_canceled=0x7f060024;
        public static final int misc_failed_save=0x7f060026;
        public static final int misc_no_button=0x7f060020;
        public static final int misc_ok_button=0x7f060021;
        public static final int misc_saved=0x7f060025;
        public static final int misc_send_button=0x7f060022;
        public static final int misc_yes_button=0x7f06001f;
        public static final int notification_title=0x7f060027;
        public static final int postjob_http_error=0x7f060053;
        public static final int settings_events_category_title=0x7f06005f;
        public static final int settings_events_dialog_log_level_default=0x7f060067;
        public static final int settings_events_dialog_log_level_title=0x7f060066;
        public static final int settings_events_enabled_summary=0x7f060061;
        public static final int settings_events_enabled_title=0x7f060060;
        public static final int settings_events_log_level_summary=0x7f060065;
        public static final int settings_events_log_level_title=0x7f060064;
        public static final int settings_events_sms_enabled_summary=0x7f060063;
        public static final int settings_events_sms_enabled_title=0x7f060062;
        public static final int settings_name=0x7f060054;
        public static final int settings_notification_category_title=0x7f060055;
        public static final int settings_notification_log_level_default=0x7f06005a;
        public static final int settings_notification_log_level_summary=0x7f060059;
        public static final int settings_notification_log_level_title=0x7f060058;
        public static final int settings_notification_sound_default=0x7f06005c;
        public static final int settings_notification_sound_title=0x7f06005b;
        public static final int settings_notification_summary=0x7f060057;
        public static final int settings_notification_title=0x7f060056;
        public static final int settings_notification_vibrate_summary=0x7f06005e;
        public static final int settings_notification_vibrate_title=0x7f06005d;
        public static final int settings_system_category_title=0x7f060068;
        public static final int settings_system_logging_verbose_summary=0x7f06006a;
        public static final int settings_system_logging_verbose_title=0x7f060069;
        public static final int smsreceiver_error_prefix=0x7f06002b;
        public static final int smsreceiver_received_intent=0x7f06002c;
        public static final int webhook_edit_activity_name=0x7f060041;
        public static final int webhook_edit_menu_cancel_label=0x7f060048;
        public static final int webhook_edit_menu_save_label=0x7f060047;
        public static final int webhook_edit_name_label=0x7f060042;
        public static final int webhook_edit_nonce_random_label=0x7f060045;
        public static final int webhook_edit_nonce_timestamp_label=0x7f060046;
        public static final int webhook_edit_secret_label=0x7f060044;
        public static final int webhook_edit_uri_label=0x7f060043;
        public static final int webhook_import_cancelled=0x7f060049;
        public static final int webhook_import_io_error=0x7f06004e;
        public static final int webhook_import_json_error=0x7f06004b;
        public static final int webhook_import_json_nonce_random_error=0x7f06004c;
        public static final int webhook_import_json_nonce_timestamp_error=0x7f06004d;
        public static final int webhook_import_saved=0x7f06004a;
        public static final int webhook_post_service_creating=0x7f060050;
        public static final int webhook_post_service_log_completed_post_prefix=0x7f06004f;
        public static final int webhook_post_service_shutting_down=0x7f060052;
        public static final int webhook_post_service_starting_webhook_post_prefix=0x7f060051;
        public static final int webhooks_list_context_menu_delete_label=0x7f06003b;
        public static final int webhooks_list_context_menu_edit_label=0x7f06003a;
        public static final int webhooks_list_context_menu_send_extra_label=0x7f060039;
        public static final int webhooks_list_context_menu_send_label=0x7f060038;
        public static final int webhooks_list_context_menu_set_events_webhook_label=0x7f06003c;
        public static final int webhooks_list_dialog_delete_message=0x7f06003e;
        public static final int webhooks_list_dialog_delete_title=0x7f06003d;
        public static final int webhooks_list_dialog_send_extra_message=0x7f060040;
        public static final int webhooks_list_dialog_send_extra_title=0x7f06003f;
        public static final int webhooks_list_empty_view=0x7f06002d;
        public static final int webhooks_list_error_dialog_title=0x7f06002f;
        public static final int webhooks_list_error_dialog_undefined=0x7f060030;
        public static final int webhooks_list_menu_about_label=0x7f060036;
        public static final int webhooks_list_menu_intentfilters_label=0x7f060037;
        public static final int webhooks_list_menu_new_label=0x7f060033;
        public static final int webhooks_list_menu_settings_label=0x7f060035;
        public static final int webhooks_list_menu_view_log_label=0x7f060034;
        public static final int webhooks_list_progress_dialog_sending_body=0x7f060032;
        public static final int webhooks_list_progress_dialog_sending_title=0x7f060031;
        public static final int webhooks_list_sent_toast=0x7f06002e;
    }
    public static final class xml {
        public static final int settings=0x7f040000;
    }
}
